### ISSUE TITLE
Showing the default UserVoice icon in the directive

### ISSUE THREAD

**Issue by ivassiliev** [chesleybrown/uservoice-trigger-directive#9]
Hi,

I would like to show the UserVoice default icon on the page instead of a text link, what would be the best way to achieve this with your version of the directive?

At the moment I have changed directive.uservoice-trigger.js from

```
if (UserVoice) {
  UserVoice.push(['addTrigger', '#' + elem.attr('id'), { mode: scope.mode, position: scope.position }]);
}
```

to

```
if (UserVoice) {
  UserVoice.push(['addTrigger',  { mode: scope.mode, position: scope.position }]);
}
```

Is the current behaviour intentional? Would you like me to submit a pull request to modify it?

Thanks,

Ilia

**Comment by jurko-gospodnetic** [comment]
That would pretty much beat the point of this UserVoice directive. If you really want the default UserVoice widget, why not just instantiate the UserVoice service in your code and call `push()` on it directly?

The idea behind this directive is to connect the trigger to a specific DOM element instead of using the default one.
